name: Veracode Static Policy Scanner

on:
  workflow_call:
    inputs:
      profile_name:
        required: true
        type: string
      moddules_to_scan:
        required: true
        type: string

jobs:
  policy_scan:
    runs-on: ubuntu-latest
    name: policy scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory

      # - name: Get the name of the downloaded files
      #   run: |
      #     artifact_file=$(ls -1 ./veracode_artifact_directory | head -n 1)
      #     echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV
      # run the policy scan action
      - name: Veracode Upload and Scan Action Step
        uses: veracode/uploadandscan-action@v0.1.0
        id: upload_and_scan
        with:
          appname: ${{ inputs.profile_name }}
          createprofile: true
          policy: 'Verademo Policy'
          version: '${{ github.run_id }}'
          filepath: ./veracode_artifact_directory/*
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          #scanpollinginterval: 30
          scantimeout: 60
          include: ${{ inputs.moddules_to_scan }}
          failbuild: true
          #teams: "Team 7, Team 5, Team A"
